/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Entidad.TramitesC;
import dominio.TramitesLN;
import dominio.UsuarioLN;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DESKTOP
 */
public class tramites extends javax.swing.JFrame {

    TramitesLN tg = new TramitesLN();
    ArrayList<TramitesC> ListaTramites = new ArrayList<>();
    TramitesC tramite;

    public tramites() {
        initComponents();
        desactivar();
    }

    private void desactivar() {
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        txtNombret.setEnabled(false);
        txtRequisitos.setEnabled(false);
        txtDuracion.setEnabled(false);
        txtCosto.setEnabled(false);
        txtDescriocion.setEnabled(false);
        txtFecha.setEnabled(false);
    }

    private void activar() {
        btnAgregar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnModificar.setEnabled(true);
        txtNombret.setEnabled(true);
        txtRequisitos.setEnabled(true);
        txtDuracion.setEnabled(true);
        txtCosto.setEnabled(true);
        txtDescriocion.setEnabled(true);
        txtFecha.setEnabled(true);
    }

    private void limpiar() {

        txtNombret.setText("");
        txtRequisitos.setText("");
        txtDuracion.setText("");
        txtCosto.setText("");
        txtDescriocion.setText("");
        txtFecha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombret = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtDescriocion = new javax.swing.JTextField();
        txtRequisitos = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Tramite");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 40));

        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        jLabel3.setText("Costo ($)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 40));

        jLabel4.setText("Requisitos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 40));

        jLabel5.setText("Duracion Estimada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 40));

        jLabel6.setText("Fecha Actualizacion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, 40));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 30));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 30));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, 30));

        jLabel7.setText("TRAMITES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
        getContentPane().add(txtNombret, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, -1));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 100, -1));

        txtDescriocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriocionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescriocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 370, 70));
        getContentPane().add(txtRequisitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 370, 60));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 110, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, 30));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        tramite = new TramitesC();

        tramite.setNombre_tramite(txtNombret.getText());
        tramite.setDescripcion(txtDescriocion.getText());
        tramite.setCosto(txtCosto.getText());
        tramite.setRequisitos(txtRequisitos.getText());

        tramite.setDuracion_Estimada(txtDuracion.getText());
        tramite.setFecha_Actualizacion(txtFecha.getText());

        int swe = tg.agregaTramites(tramite);
        if (swe == 1) {
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            limpiar();

            Entidad.TramitesC frm = new Entidad.TramitesC();
            frm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Registro no exitoso");

        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        tramite = new Entidad.TramitesC();

        tramite.setNombre_tramite(txtNombret.getText());
        tramite.setDescripcion(txtDescriocion.getText());
        tramite.setCosto(txtCosto.getText());
        tramite.setRequisitos(txtRequisitos.getText());
          tramite.setDuracion_Estimada(txtDuracion.getText());
        tramite.setFecha_Actualizacion(txtFecha.getText());

        int editar = tg.modificaTramites(tramite);
        if (editar == 1) {
            JOptionPane.showMessageDialog(null, "Tramite actualizado satisfactoriamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Tramite no actualizado correctamente");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        tramite = new Entidad.TramitesC();
        String nombre = txtNombret.getText();
        try {
            int editar = tg.eliminaTramites(nombre);
            if (editar == 1) {
                JOptionPane.showMessageDialog(null, "Oficina eliminado correctamente");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Oficina no eliminado correctamente");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar" + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Principal frm = new Principal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar();
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = txtNombret.getText();
        TramitesC tramite = tg.buscaTramite(nombre);

        if (tramite != null) {

            txtDescriocion.setText(tramite.getDescripcion());
            txtCosto.setText(tramite.getCosto());
            txtRequisitos.setText(tramite.getRequisitos());
            txtDuracion.setText(tramite.getDuracion_Estimada());
            txtFecha.setText(tramite.getFecha_Actualizacion());

        } else {
            JOptionPane.showMessageDialog(null, "Tramite no registrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDescriocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriocionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriocionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tramites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescriocion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombret;
    private javax.swing.JTextField txtRequisitos;
    // End of variables declaration//GEN-END:variables
}
