package presentacion;

import entidad.OficinasC;
import persistencia.Conexion;
import dominio.OficinasLN;
import dominio.UsuarioLN;
import java.beans.Statement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author DESKTOP
 */
public class oficinas extends javax.swing.JFrame {

    UsuarioLN user = new UsuarioLN();
//    ArrayList<OficinasC> ListaOficinas = new ArrayList<>();
//    OficinasC oficina;
    OficinasC oficina;
    OficinasLN bo = new OficinasLN();

    public oficinas() {
        initComponents();
        desactivar();
    }

    private void desactivar() {
        btnAgregar.setEnabled(false);
        btnEliminarç.setEnabled(false);
        btnModificar.setEnabled(false);
        btnBuscar.setEnabled(false);
        txtNombreO.setEnabled(false);
        txtDescripcion.setEnabled(false);

    }

    private void activar() {
        btnAgregar.setEnabled(true);
        btnEliminarç.setEnabled(true);
        btnModificar.setEnabled(true);
        txtNombreO.setEnabled(true);
        txtDescripcion.setEnabled(true);
        btnBuscar.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminarç = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtNombreO = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("OFICINAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setText("Nombre_Oficina");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("DESCRIPCION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        btnEliminarç.setText("ELIMINAR");
        btnEliminarç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarçActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarç, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
        getContentPane().add(txtNombreO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 260, 90));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        oficina = new OficinasC();
        oficina.setNombre(txtNombreO.getText());
        oficina.setDescripcion(txtDescripcion.getText());

        int swe = bo.agregaOficina(oficina);
        if (swe == 1) {
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            txtDescripcion.setText("");
            txtNombreO.setText("");

            entidad.OficinasC frm = new entidad.OficinasC();
            frm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Registro no exitoso");

        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Principal frm = new Principal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar();
        txtDescripcion.setText("");
        txtNombreO.setText("");

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String nombre = txtNombreO.getText();
        OficinasC oficina = bo.buscaOficina(nombre);

        if (oficina != null) {

            txtDescripcion.setText(oficina.getDescripcion());

        } else {
            JOptionPane.showMessageDialog(null, "Oficna no registrado");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        oficina = new entidad.OficinasC();

        oficina.setNombre(txtNombreO.getText());
        oficina.setDescripcion(txtDescripcion.getText());
////        ListaOficinas.add(oficina);
       try{
        int edita = bo.modificaOficina(oficina);
        if (edita == 1) {
            JOptionPane.showMessageDialog(null, "Oficina actualizado correctamente");
            txtNombreO.setEnabled(false);
            txtDescripcion.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Oficina no actualizado correctamente");
        }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"No se pudo actualizar" + ex.getMessage());
       }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarçActionPerformed
        oficina = new entidad.OficinasC();
        String nombre = txtNombreO.getText();
        try {
            int editar = bo.eliminaOficina(nombre);
            if (editar == 1) {
                JOptionPane.showMessageDialog(null, "Oficina eliminado correctamente");
                txtNombreO.setEnabled(false);
                txtDescripcion.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Oficina no eliminado correctamente");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar" + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarçActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oficinas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarç;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreO;
    // End of variables declaration//GEN-END:variables

    private TableCellRenderer RenderImagen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
